export const Columns=[
    {
        Header:'Name',
        accessor:'Name'    
    },
    {
        Header:'Entity',
        accessor:'Entity'    
    },
    {
        Header:'Location',
        accessor:'Location'    
    },
    {
        Header:'Expertise',
        accessor:'Expertise'    
    },
    {
        Header:'Date',
        accessor:'Date'    
    },{
        Header:'Firm',
        accessor:'Firm'    
    }
]